<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>    
    <IsAotCompatible>true</IsAotCompatible>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <Version>1.0.0-preview.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" />
    <PackageReference Include="Avae.Services" />
    <PackageReference Include="Avae.ViewModels" />
  </ItemGroup>
  
</Project>
